baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Oui Data"
  subtitle    = "Devenir Data Scientist"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["screen.css"]
  RSSLink = ""

  #twitterName = "faketryghost"
  #fbName = "fakeghost"
  #githubName = "eueung"
  linkedinName = "nicolasbrunn"
  #mediumName = ""

  logo = "/upload/LogoMakr_8KeMkl.png"
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Nicolas Br"
  authorAvatar = "upload/photo.JPG"
  authorLocation = "La Défense"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Data Scientist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Model"
  url = "/model/"
  weight = 100

#[[menu.main]]
#  name = "Categories"
#  url = "/categories/"
#  weight = 99

# [[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 95


